Cred 346 create pdf service copying atira api pdf generation logic
CrediNord/pdf-service pull request #1
Opened 2021-06-24 06:09 UTC by rgalimskii-cn

https://credinord.atlassian.net/browse/CRED-346

**Reasons for PR**:

- centralized and fast PDF generator is needed

**PR Change List**:

- copypasted ATIRA API PDF generation logic
- extracted browser init to a separate provider so it's kept in memory after the first call (not the best solution, will be improved further)
- introduced POST /internal/pdf endpoint

2021-06-24 11:37 UTC, rgalimskii-cn commented on package.json
> +    "forceExit": true
it seems the puppeteer isn't closed properly even with proper teardown. This is the trade-off to make the build pass. I'll mock Chrome instantiation once it's extracted to a separate docker.

2021-06-24 11:37 UTC, rgalimskii-cn commented on test/jest-e2e.json
> +  "forceExit": true
see https://github.com/CrediNord/pdf-service/pull/1/files#r657867721

2021-06-24 16:03 UTC, zun-credinord requested changes

2021-06-24 16:03 UTC, zun-credinord commented on src/internal/pdf/browser.provider.spec.ts
> +    provider = module.get<TestBrowserProvider>(TestBrowserProvider);
this might be a bit overkill, should `new TestBrowserProvider()` be enough?

2021-06-24 16:03 UTC, zun-credinord commented on src/internal/pdf/browser.provider.spec.ts
> +      expect(provider.getBrowserInstance().process().pid).toEqual(browser.process().pid);
`provider.getBrowserInstance()` can be extract to var?

2021-06-24 16:03 UTC, zun-credinord commented on src/internal/pdf/browser.provider.spec.ts
> +    done();
do we really need `done()` here?

2021-06-30 07:38 UTC, zun-credinord requested changes

2021-06-30 07:38 UTC, zun-credinord commented on src/internal/pdf/browser.provider.ts
> +      this.spawnNewBrowserInstance(),
this is bug, use `defer` here

2021-06-30 07:38 UTC, zun-credinord commented on src/internal/pdf/browser.provider.ts
> +      ),
is the another param of `iif` left missing on purpose?

2021-06-30 07:38 UTC, zun-credinord commented on src/internal/pdf/pdf.controller.spec.ts
> +    controller = module.get<PdfController>(PdfController);
`new PdfController()` might be enough to create the test instance

2021-06-30 07:38 UTC, zun-credinord commented on src/internal/pdf/pdf.controller.ts
> +    }
why dont we use rxjs here?

2021-06-30 07:38 UTC, zun-credinord commented on src/internal/pdf/pdf.service.ts
> +        return pdfBuffer;
might be converted into rxjs flow so we do not have mixed code style

2021-06-30 07:38 UTC, zun-credinord commented on test/pdf.e2e-spec.ts
> +      imports: [PdfModule],
enable logger request context by add `CredinordRequestContextAwareModule` here

2021-06-30 07:38 UTC, zun-credinord commented on src/root/routes.ts
> -            path: '/hello',
let keep both public hello controllers so we can have a way to verify the service is up.

2021-06-30 07:38 UTC, zun-credinord commented on test/pdf.e2e-spec.ts
> +    request(app.getHttpServer())
can we `return` here so we do not need to use `done`?

2021-07-01 06:25 UTC, envil commented on src/internal/pdf/browser.provider.ts
> +      ),
In that case EMPTY will be the default observable to use.

2021-07-01 06:29 UTC, envil commented on src/internal/pdf/pdf.controller.spec.ts
> +    controller = module.get<PdfController>(PdfController);
I think it's easier this way otherwise we have to initiate the PdfService manually.

2021-07-01 06:32 UTC, zun-credinord commented on src/internal/pdf/pdf.controller.spec.ts
> +    controller = module.get<PdfController>(PdfController);
really, did we also initiate the PdfService manually as well in the current code?

2021-07-01 06:34 UTC, zun-credinord commented on src/internal/pdf/browser.provider.ts
> +      ),
then should we declare it here so it is not hidden to developers or make us have to remember api param?

2021-07-01 06:35 UTC, envil commented on src/internal/pdf/pdf.controller.spec.ts
> +    controller = module.get<PdfController>(PdfController);
Where is that?

2021-07-01 06:37 UTC, envil commented on src/internal/pdf/pdf.controller.spec.ts
> +    controller = module.get<PdfController>(PdfController);
Not a strong opinion but I think it's unnecessary, similar to an if without an else. If the else is empty then should we include it or not?

2021-07-01 06:45 UTC, zun-credinord requested changes

2021-07-01 06:45 UTC, zun-credinord commented on src/internal/pdf/pdf.controller.spec.ts
> +          useValue: { generatePdfBuffer: generatePdfBufferMock },
use `jest-mock-extended` here so we do not need to create the mock instance manually. This is not type-safe as well. And it cleans up the code as well.

2021-07-01 06:45 UTC, zun-credinord commented on src/internal/pdf/pdf.controller.spec.ts
> +    controller = module.get<PdfController>(PdfController);
line 21

2021-07-01 06:46 UTC, envil commented on src/internal/pdf/browser.provider.ts
> +      ),
Not a strong opinion but I think it's unnecessary. It's like an if block without an else, if the else block is empty then should we include it or not?

2021-07-01 06:51 UTC, zun-credinord commented on src/internal/pdf/browser.provider.ts
> +      ),
i think it is unnecessary when the func does not return the value (call and forget). But in this case it is returning, so provide clarity might be better.

2021-07-01 06:52 UTC, zun-credinord commented on src/internal/pdf/pdf.controller.spec.ts
> +          useValue: { generatePdfBuffer: generatePdfBufferMock },
https://www.npmjs.com/package/jest-mock-extended

2021-07-01 06:53 UTC, envil commented on src/internal/pdf/browser.provider.ts
> +      ),
sure, let's do that

2021-07-01 11:12 UTC, envil commented on src/internal/pdf/pdf.service.ts
> +        return pdfBuffer;
The puppeteer api is imperative so it's a bit ugly trying to convert this into RxJS
```
    return from(this.browser.get()).pipe(
      tap(() => {
        this.logger.log({
          message: 'Starting generating PDF file',
          payload: pdfGenerationDto,
        });
      }),
      concatMap(browser => browser.newPage()),
      concatMap(page => {
        return from(
          page.setContent(pdfGenerationDto.body, { waitUntil: 'domcontentloaded' }),
        ).pipe(mapTo(page));
      }),
      concatMap(page =>
        from(page.pdf(options)).pipe(
          concatMap(buffer => from(page.close()).pipe(mapTo(buffer))),
        ),
      ),
      tap(() => {
        this.logger.log({
          message: 'PDF generation succeeded',
        });
      }),
    );
 ```

2021-07-01 11:37 UTC, zun-credinord commented on src/internal/pdf/pdf.service.ts
> +        return pdfBuffer;
it can be written as:

```
  mergeMap(browser => browser.newPage()),
      mergeMap(page => {
        return of(1).pipe(
          mergeMap(() =>
            page.setContent(pdfGenerationDto.body, { waitUntil: 'domcontentloaded' }),
          ),
          mergeMap(() => page.pdf(options)),
          tap(x => page.close()),
        );
      }),
```

but you feel this is still ugly, we can keep the current code.

2021-07-01 11:50 UTC, zun-credinord commented on src/internal/pdf/pdf.service.ts
> +        await page.close();
we might need try/catch here to still be able to return buffer

2021-07-01 12:34 UTC, zun-credinord requested changes

2021-07-01 12:34 UTC, zun-credinord commented on src/internal/pdf/browser.provider.spec.ts
> +    provider = new TestBrowserProvider(new CredinordContextLogger());
new CredinordContextLogger() can be replaced with `loggerFactory()`

2021-07-01 12:34 UTC, zun-credinord commented on src/internal/pdf/browser.provider.spec.ts
> +    provider = new TestBrowserProvider(new CredinordContextLogger());
same in other places

2021-07-01 12:34 UTC, zun-credinord commented on src/internal/pdf/pdf.service.spec.ts
> +    service = module.get<PdfService>(PdfService);
use `new PdfService()`

2021-07-01 12:34 UTC, zun-credinord commented on test/mocks/browser.mock.ts
> +import { Browser, Page } from 'puppeteer';
can we use the mock extended lib in this file?

2021-07-01 12:34 UTC, zun-credinord commented on test/pdf.e2e-spec.ts
> +    request(app.getHttpServer())
if we do not return or use done, how can the test be sure to be completed successfully, especially we are enabling `forceExit` flag with jest

2021-07-01 12:50 UTC, envil commented on src/internal/pdf/pdf.controller.ts
> +    }
The download case is a bit different since we have to use the Response api which is imperative, so I think it's more suitable to use async/await here.

2021-07-01 12:50 UTC, envil commented on test/pdf.e2e-spec.ts
> +    request(app.getHttpServer())
We're returning, it's shorthand syntax.

2021-07-01 12:51 UTC, envil commented on src/internal/internal.module.ts
> +  imports: [PdfModule],
Fixed

2021-07-01 12:51 UTC, envil commented on src/internal/pdf/browser.provider.spec.ts
> +    provider = module.get<TestBrowserProvider>(TestBrowserProvider);
Fixed

2021-07-01 12:51 UTC, envil commented on src/internal/pdf/browser.provider.spec.ts
> +      expect(provider.getBrowserInstance().process().pid).toEqual(browser.process().pid);
Fixed

2021-07-01 12:52 UTC, envil commented on src/internal/pdf/browser.provider.spec.ts
> +    done();
Removed

2021-07-01 12:52 UTC, envil commented on src/internal/pdf/browser.provider.ts
> +      this.spawnNewBrowserInstance(),
Fixed

2021-07-01 12:52 UTC, envil commented on src/internal/pdf/pdf.controller.spec.ts
> +    controller = module.get<PdfController>(PdfController);
Fixed

2021-07-01 12:52 UTC, envil commented on test/pdf.e2e-spec.ts
> +      imports: [PdfModule],
Fixed

2021-07-01 12:52 UTC, envil commented on src/internal/pdf/pdf.controller.spec.ts
> +          useValue: { generatePdfBuffer: generatePdfBufferMock },
Fixed

2021-07-01 12:52 UTC, envil commented on src/internal/pdf/pdf.service.ts
> +        await page.close();
Fixed

2021-07-01 12:52 UTC, envil commented on src/internal/pdf/browser.provider.spec.ts
> +    provider = new TestBrowserProvider(new CredinordContextLogger());
Fixed

2021-07-01 12:55 UTC, envil commented on src/internal/pdf/pdf.service.spec.ts
> +    service = module.get<PdfService>(PdfService);
Fixed

2021-07-01 12:56 UTC, envil commented on test/mocks/browser.mock.ts
> +import { Browser, Page } from 'puppeteer';
Removed the file

2021-07-01 13:09 UTC, envil commented on src/root/routes.ts
> -            path: '/hello',
Added back

2021-07-01 13:10 UTC, envil commented
@zun-credinord fixed all the code review comments

2021-07-01 13:22 UTC, zun-credinord commented on test/pdf.e2e-spec.ts
> +    request(app.getHttpServer())
oh sorry, my bad

2021-07-01 13:24 UTC, zun-credinord approved these changes
Great work! @rgalimskii-cn and @envil

2021-07-01 18:12 UTC, merged